export const userInfo = {
  userInfo: 'max-w-[250px] w-full',
  wrapper: 'w-full p-[20px] shadow-card bg-card rounded-[8px]',
  sameFlexBetween: 'flex justify-between items-center',
  sameFlexTogether: 'flex justify-start items-center',
  box: 'flex items-center justify-between border-b-2 pb-[10px] border-cardBorder',
  user: 'flex items-center justify-start gap-[10px]',
  userName: 'text-white text-[14px] font-medium ',
  userFriends: 'text-gray text-[12px]',
  addFriend: 'cursor-pointer hover:scale-[1.1] transition-all duration-100',
  userAdditional: 'flex items-end gap-[10px]',
  userData: 'text-white text-[12px] text-gray',
  viewsWrapper: 'flex justify-between items-center',
  contactDetail: 'text-white text-[14px] mb-[10px]',
  socialTitle: 'text-white text-[14px] font-medium inline-block',
  socialLink: 'text-gray text-[12px] block',
  edit: 'transition-all duration-100 hover:scale-[1.1] cursor-pointer',
};
